"""
cutsheet_preprocessor.py — Automated cutsheet normalization at upload time.

Applies STATUS_MAP rules, strips section-header rows, counts A/Z optics
independently.  Source-agnostic: works on any DataFrame regardless of whether
it came from an xlsx upload or a Google Sheet fetch.

The canonical status mapping was generated by Claude in Excel from the
Ellendale MASTER-US-CENTRAL-08A cutsheet (2026-04-22).  New sites may
introduce unknown status values — those land as UNKNOWN and get logged so
the map can be expanded.
"""

from __future__ import annotations

import logging
import math
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Canonical status enum — the 8 possible values after normalization
# ---------------------------------------------------------------------------

COMPLETE = "COMPLETE"
NOT_TERMINATED = "NOT_TERMINATED"
NOT_RUN = "NOT_RUN"
# NOT_RUN_PRIORITY collapsed into NOT_RUN to match cutsheet_profiles.py
ADDITION = "ADDITION"
HUMAN_VERIFIED = "HUMAN_VERIFIED"
LLDP_PASSED = "LLDP_PASSED"
LLDP_FAILED = "LLDP_FAILED"
IN_PROGRESS = "IN_PROGRESS"
PENDING = "PENDING"
BLANK = "BLANK"
SECTION_HEADER = "SECTION_HEADER"
UNKNOWN = "UNKNOWN"

# ---------------------------------------------------------------------------
# STATUS_MAP — built from Claude in Excel output (171 rows, 2026-04-22)
#
# Keys are EXACT original status strings (case-sensitive match first,
# case-insensitive fallback).  Values are one of the canonical enums above.
# ---------------------------------------------------------------------------

STATUS_MAP: Dict[str, str] = {
    # ── Real cable statuses ──────────────────────────────────────────────
    "Cable Is Ran: Complete": COMPLETE,
    "Human Verified": HUMAN_VERIFIED,
    "Cable Is Ran: Not Terminated": NOT_TERMINATED,
    "Cable Not Run": NOT_RUN,
    "Cable Not Run: Priority": NOT_RUN,
    "Addition": ADDITION,
    # ── Canonical values (self-mapping for pre-cleaned sheets) ─────────
    "COMPLETE": COMPLETE,
    "NOT_TERMINATED": NOT_TERMINATED,
    "NOT_RUN": NOT_RUN,
    "NOT_RUN_PRIORITY": NOT_RUN,  # pre-cleaned sheets may have this value
    "ADDITION": ADDITION,
    "HUMAN_VERIFIED": HUMAN_VERIFIED,
    "LLDP_PASSED": LLDP_PASSED,
    "LLDP_FAILED": LLDP_FAILED,
    "IN_PROGRESS": IN_PROGRESS,
    "PENDING": PENDING,
    "BLANK": BLANK,
    # ── Fuzzy variants (lowercase keys for case-insensitive fallback) ────
    "cable is ran: complete": COMPLETE,
    "cable is ran complete": COMPLETE,
    "cable is ran:complete": COMPLETE,
    "cable is ran - complete": COMPLETE,
    "cable ran complete": COMPLETE,
    "cable complete": COMPLETE,
    "complete": COMPLETE,
    "human verified": HUMAN_VERIFIED,
    "human: verified": HUMAN_VERIFIED,
    "manually verified": HUMAN_VERIFIED,
    "cable is ran: not terminated": NOT_TERMINATED,
    "cable is ran not terminated": NOT_TERMINATED,
    "cable is ran:not terminated": NOT_TERMINATED,
    "cable is ran - not terminated": NOT_TERMINATED,
    "not terminated": NOT_TERMINATED,
    "cable not run": NOT_RUN,
    "cable not ran": NOT_RUN,
    "no cable": NOT_RUN,
    "cable not run: priority": NOT_RUN,
    "cable not run:priority": NOT_RUN,
    "cable not run - priority": NOT_RUN,
    "addition": ADDITION,
    "no label & not yet run": NOT_RUN,
    "no label and not yet run": NOT_RUN,
    # LLDP variants (from Quincy and other operational sites)
    # Kept as distinct canonical values so burndown/status queries can
    # distinguish LLDP-verified from cable-verified.
    "lldp: passed": LLDP_PASSED,
    "lldp:  passed": LLDP_PASSED,
    "lldp passed": LLDP_PASSED,
    "lldp:passed": LLDP_PASSED,
    "lldp - passed": LLDP_PASSED,
    "LLDP:  Passed": LLDP_PASSED,
    "LLDP Passed": LLDP_PASSED,
    "lldp: failed": LLDP_FAILED,
    "lldp:  failed": LLDP_FAILED,
    "lldp failed": LLDP_FAILED,
    "lldp:failed": LLDP_FAILED,
    "lldp - failed": LLDP_FAILED,
    "LLDP:  Failed": LLDP_FAILED,
    "LLDP Failed": LLDP_FAILED,
    # Misc statuses (from cutsheet_profiles.py)
    "in progress": IN_PROGRESS,
    "pending": PENDING,
    # ── Section headers (from Ellendale STATUS_MAP tab) ──────────────────
    "BACKBONE BFR": SECTION_HEADER,
    "BACKBONE MGMT": SECTION_HEADER,
    "BACKBONE/OPTICAL MGMT": SECTION_HEADER,
    "CON-01 Grid A Pod 1": SECTION_HEADER,
    "CON-01 Grid A Pod 2": SECTION_HEADER,
    "CON-01 Grid A Pod 3": SECTION_HEADER,
    "CON-01 Grid A Pod 4": SECTION_HEADER,
    "CON-01 Grid A Rack 230": SECTION_HEADER,
    "CON-01 Grid A1 Rack 222": SECTION_HEADER,
    "CON-01 Grid A1 Rack 223": SECTION_HEADER,
    "CON-01 Grid A1 Rack 224": SECTION_HEADER,
    "CON-01 Grid A1 Rack 225": SECTION_HEADER,
    "CON-01 Grid A1 Rack 226": SECTION_HEADER,
    "CON-01 Grid A1 Rack 227": SECTION_HEADER,
    "CON-01 Grid A1 Rack 228": SECTION_HEADER,
    "CON-01 Grid A1 Rack 229": SECTION_HEADER,
    "CON-01 Grid A2 Rack 232": SECTION_HEADER,
    "CON-01 Grid A2 Rack 233": SECTION_HEADER,
    "CON-01 Grid A2 Rack 234": SECTION_HEADER,
    "CON-01 Grid A2 Rack 235": SECTION_HEADER,
    "CON-01 Grid A2 Rack 236": SECTION_HEADER,
    "CON-01 Grid A2 Rack 237": SECTION_HEADER,
    "CON-01 Grid A2 Rack 238": SECTION_HEADER,
    "CON-01 Grid A2 Rack 239": SECTION_HEADER,
    "CON-01 Grid A2 Rack 240": SECTION_HEADER,
    "CON-01 Grid B Pod 1": SECTION_HEADER,
    "CON-01 Grid B Rack 50": SECTION_HEADER,
    "CON-01 Grid B1 Rack 46": SECTION_HEADER,
    "CON-01 Grid C Rack 67": SECTION_HEADER,
    "CON-01 Grid C Rack 68": SECTION_HEADER,
    "CON-01 Grid C Rack 69": SECTION_HEADER,
    "CON-01 Grid C Rack 70": SECTION_HEADER,
    "CON-01 Grid C1": SECTION_HEADER,
    "CON-01 Grid C2": SECTION_HEADER,
    "CON-01 Grid C3": SECTION_HEADER,
    "CON-01 Grid D Rack 107": SECTION_HEADER,
    "CON-01 Grid D Rack 108": SECTION_HEADER,
    "CON-01 Grid D Rack 109": SECTION_HEADER,
    "CON-01 Grid D Rack 110": SECTION_HEADER,
    "CON-01 Grid D1": SECTION_HEADER,
    "CON-01 Grid D2": SECTION_HEADER,
    "CON-01 Grid D3": SECTION_HEADER,
    "CON-01 Grid E Pod 1": SECTION_HEADER,
    "CON-01 Grid E Rack 10": SECTION_HEADER,
    "CON-01 Grid E1 Rack 2": SECTION_HEADER,
    "CON-01 Grid E1 Rack 3": SECTION_HEADER,
    "CON-01 Grid E1 Rack 4": SECTION_HEADER,
    "CON-01 Grid E1 Rack 5": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 222": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 223": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 224": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 225": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 226": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 227": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 228": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A1 Rack 229": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 232": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 233": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 234": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 235": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 236": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 237": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 238": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 239": SECTION_HEADER,
    "Compute Mgmt In-Row Grid A2 Rack 240": SECTION_HEADER,
    "Compute Mgmt In-Row Grid B1 Rack 46": SECTION_HEADER,
    "Compute Mgmt In-Row Grid E1 Rack 2": SECTION_HEADER,
    "Compute Mgmt In-Row Grid E1 Rack 3": SECTION_HEADER,
    "Compute Mgmt In-Row Grid E1 Rack 4": SECTION_HEADER,
    "Compute Mgmt In-Row Grid E1 Rack 5": SECTION_HEADER,
    "DH202 :: <<<<< A1": SECTION_HEADER,
    "DH202 :: <<<<< A2": SECTION_HEADER,
    "DH202 :: <<<<< B1": SECTION_HEADER,
    "DH202 :: A3": SECTION_HEADER,
    "DH202 :: A4": SECTION_HEADER,
    "DH202 :: C1": SECTION_HEADER,
    "DH202 :: C2": SECTION_HEADER,
    "DH202 :: C3": SECTION_HEADER,
    "DH202 OVERFLOW T0 ROCE MGMT": SECTION_HEADER,
    "DH202 T1 ROCE MGMT": SECTION_HEADER,
    "DH202 T2 ROCE MGMT": SECTION_HEADER,
    "DH204 :: D1": SECTION_HEADER,
    "DH204 :: D2": SECTION_HEADER,
    "DH204 :: D3": SECTION_HEADER,
    "DH204 :: E1": SECTION_HEADER,
    "DH204 OVERFLOW T0 ROCE MGMT": SECTION_HEADER,
    "DH204 T1 ROCE MGMT": SECTION_HEADER,
    "DH204 T2 ROCE MGMT": SECTION_HEADER,
    "FBS": SECTION_HEADER,
    "GRID-AGG-A": SECTION_HEADER,
    "GRID-AGG-B": SECTION_HEADER,
    "GRID-AGG-C": SECTION_HEADER,
    "GRID-AGG-D": SECTION_HEADER,
    "GRID-AGG-E": SECTION_HEADER,
    "INFRA-DIST-A": SECTION_HEADER,
    "INFRA-DIST-B": SECTION_HEADER,
    "INFRA-DIST-C": SECTION_HEADER,
    "INFRA-DIST-D": SECTION_HEADER,
    "INFRA-DIST-E": SECTION_HEADER,
    "MGMT-CORE": SECTION_HEADER,
    "MGMT-DIST": SECTION_HEADER,
    "NET-01 Grid A Pod 1": SECTION_HEADER,
    "NET-01 Grid A Pod 2": SECTION_HEADER,
    "NET-01 Grid A Rack 230": SECTION_HEADER,
    "NET-01 Grid B Pod 1": SECTION_HEADER,
    "NET-01 Grid B Rack 50": SECTION_HEADER,
    "NET-01 Grid C Rack 67": SECTION_HEADER,
    "NET-01 Grid C Rack 68": SECTION_HEADER,
    "NET-01 Grid C Rack 69": SECTION_HEADER,
    "NET-01 Grid C Rack 70": SECTION_HEADER,
    "NET-01 Grid D Rack 107": SECTION_HEADER,
    "NET-01 Grid D Rack 108": SECTION_HEADER,
    "NET-01 Grid D Rack 109": SECTION_HEADER,
    "NET-01 Grid D Rack 110": SECTION_HEADER,
    "NET-01 Grid E Pod 1": SECTION_HEADER,
    "NET-01 Grid E Rack 10": SECTION_HEADER,
    # "No Label & Not Yet Run" is a real cable status (NOT_RUN), not a header.
    # Handled in the fuzzy variants block above.
    "OOB-FW": SECTION_HEADER,
    "POD-DIST-C 1": SECTION_HEADER,
    "POD-DIST-C 2": SECTION_HEADER,
    "POD-DIST-C 3": SECTION_HEADER,
    "POD-DIST-D 1": SECTION_HEADER,
    "POD-DIST-D 2": SECTION_HEADER,
    "POD-DIST-D 3": SECTION_HEADER,
    "RACK 43 NET + CON": SECTION_HEADER,
    "RACK 44 NET + CON": SECTION_HEADER,
    "RACK 51 NET + CON": SECTION_HEADER,
    "RACK 52 NET + CON": SECTION_HEADER,
    "RACK 53 NET + CON": SECTION_HEADER,
    "RACK 54 NET + CON": SECTION_HEADER,
    "RACK 55 NET + CON": SECTION_HEADER,
    "RACK 56 NET + CON": SECTION_HEADER,
    "RACK 57 NET + CON": SECTION_HEADER,
    "RACK 58 NET + CON": SECTION_HEADER,
    "RACK 59 NET + CON": SECTION_HEADER,
    "ROCE INFRA AGGS DH202": SECTION_HEADER,
    "ROCE INFRA AGGS DH204": SECTION_HEADER,
    "STOR INFRA-DIST A3": SECTION_HEADER,
    "STOR NET-01 Grid A Pod 3": SECTION_HEADER,
    "STOR NET-01 Grid A Pod 4": SECTION_HEADER,
    "TIER-1 TO TIER-0 A1": SECTION_HEADER,
    "TIER-1 TO TIER-0 A2": SECTION_HEADER,
    "TIER-1 TO TIER-0 A3 (T0 MULTIPLIER X3)": SECTION_HEADER,
    "TIER-1 TO TIER-0 A4 (T0 MULTIPLIER X3)": SECTION_HEADER,
    "TIER-1 TO TIER-0 B1": SECTION_HEADER,
    "TIER-1 TO TIER-0 C1": SECTION_HEADER,
    "TIER-1 TO TIER-0 C2": SECTION_HEADER,
    "TIER-1 TO TIER-0 C3": SECTION_HEADER,
    "TIER-1 TO TIER-0 D1": SECTION_HEADER,
    "TIER-1 TO TIER-0 D2": SECTION_HEADER,
    "TIER-1 TO TIER-0 D3": SECTION_HEADER,
    "TIER-1 TO TIER-0 E1 (T0 MULTIPLIER X1)": SECTION_HEADER,
    "TIER-2 TO TIER-1 A": SECTION_HEADER,
    "TIER-2 TO TIER-1 B": SECTION_HEADER,
    "TIER-2 TO TIER-1 C": SECTION_HEADER,
    "TIER-2 TO TIER-1 D": SECTION_HEADER,
    "TIER-2 TO TIER-1 GRID:E (T1 MULTIPLIER X2)": SECTION_HEADER,
    "TIER-3 TO TIER-2 1 A": SECTION_HEADER,
    "TIER-3 TO TIER-2 1 B": SECTION_HEADER,
    "TIER-3 TO TIER-2 1 C": SECTION_HEADER,
    "TIER-3 TO TIER-2 1 D": SECTION_HEADER,
    "TIER-3 TO TIER-2 1 E": SECTION_HEADER,
    # "a" and "b" were in the original Claude in Excel output but are garbage
    # entries (test artifacts). Removed to avoid stripping real data rows.
}

# Build a lowercase lookup for case-insensitive fallback
_STATUS_MAP_LOWER: Dict[str, str] = {k.lower(): v for k, v in STATUS_MAP.items()}

# ---------------------------------------------------------------------------
# Optic column names — these are the raw column names we look for
# ---------------------------------------------------------------------------

_A_OPTIC_CANDIDATES = ("A-OPTIC", "A_OPTIC", "a-optic", "a_optic")
_Z_OPTIC_CANDIDATES = ("Z-OPTIC", "Z_OPTIC", "z-optic", "z_optic")
_STATUS_CANDIDATES = ("STATUS", "status", "Status")


def _find_col(df: pd.DataFrame, candidates: tuple) -> Optional[str]:
    """Return the first column name from candidates that exists in df."""
    for c in candidates:
        if c in df.columns:
            return c
    return None


def _safe_str(val) -> str:
    """Convert a value to string, treating NaN/None as empty."""
    if val is None:
        return ""
    if isinstance(val, float) and math.isnan(val):
        return ""
    return str(val).strip()


# ---------------------------------------------------------------------------
# R36: Topology name patterns for section header promotion
# Only UNKNOWN+empty-optic rows matching these patterns get promoted to
# SECTION_HEADER.  Everything else stays UNKNOWN.
# ---------------------------------------------------------------------------

import re as _re

_TOPOLOGY_PATTERN = _re.compile(
    r"(?i)"
    r"(?:"
    r"TIER|GRID|CON-\d|NET-\d|RACK\s*\d|DH\d|SPINE|LEAF|FDP|CDU|PDU|TOR|"
    r"FBS|MGMT|DIST|AGG|ROCE|INFRA|BACKBONE|STOR|POD-DIST|OOB|NVLINK|GPU|"
    r"OVERFLOW|LOCODE"
    r")",
)

# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------

def classify_status(raw_status: str) -> str:
    """Map a raw STATUS string to a canonical value.

    Resolution order:
    1. Exact match against STATUS_MAP
    2. Case-insensitive match against _STATUS_MAP_LOWER
    3. Return UNKNOWN (caller decides what to do)
    """
    if not raw_status:
        return BLANK
    # Exact match first (preserves case-sensitive section header keys)
    if raw_status in STATUS_MAP:
        return STATUS_MAP[raw_status]
    # Case-insensitive fallback
    lower = raw_status.lower().strip()
    if not lower:
        return BLANK
    return _STATUS_MAP_LOWER.get(lower, UNKNOWN)


def normalize_cutsheet_df(df: pd.DataFrame) -> Tuple[pd.DataFrame, Dict[str, Any]]:
    """Normalize a raw cutsheet DataFrame.

    Adds STATUS_CANONICAL column, identifies section headers vs real data,
    and strips section-header rows.

    Returns:
        (clean_df, stats) where stats has keys:
        - rows_original: total rows in input
        - rows_stripped: section header rows removed
        - rows_blank: rows with BLANK status
        - rows_clean: rows in output
        - unknown_statuses: list of (value, count) for any UNKNOWN mappings
        - section_names: list of section header values found (for topology)
    """
    status_col = _find_col(df, _STATUS_CANDIDATES)
    if status_col is None:
        log.warning("No STATUS column found in DataFrame — skipping normalization")
        return df.copy(), {
            "rows_original": len(df),
            "rows_stripped": 0,
            "rows_blank": 0,
            "rows_clean": len(df),
            "unknown_statuses": [],
            "section_names": [],
        }

    result = df.copy()
    rows_original = len(result)

    # Vectorized: clean the status column
    raw_status = result[status_col].fillna("").astype(str).str.strip()
    # Replace "nan" strings from pandas NaN conversion
    raw_status = raw_status.where(raw_status.str.lower() != "nan", "")

    # Classify each status value — vectorized via .map() with fallback
    # Build a unique-value mapping to avoid per-row function calls
    unique_vals = raw_status.unique()
    val_to_canonical = {}
    for v in unique_vals:
        val_to_canonical[v] = classify_status(v)

    result["STATUS_CANONICAL"] = raw_status.map(val_to_canonical)

    # Heuristic fallback for UNKNOWN: if optic columns are both empty,
    # it's almost certainly a section header
    a_optic_col = _find_col(result, _A_OPTIC_CANDIDATES)
    z_optic_col = _find_col(result, _Z_OPTIC_CANDIDATES)

    if a_optic_col and z_optic_col:
        unknown_mask = result["STATUS_CANONICAL"] == UNKNOWN
        a_empty = result[a_optic_col].fillna("").astype(str).str.strip().eq("")
        z_empty = result[z_optic_col].fillna("").astype(str).str.strip().eq("")
        both_empty = a_empty & z_empty

        # R36: UNKNOWN + no optics + matches topology pattern = section header.
        # Without the topology check, notes rows and partial data rows get
        # wrongly promoted to section headers and stripped.
        candidates = unknown_mask & both_empty
        if candidates.any():
            topo_match = raw_status.str.contains(
                _TOPOLOGY_PATTERN, na=False
            )
            result.loc[candidates & topo_match, "STATUS_CANONICAL"] = SECTION_HEADER
            # Candidates that don't match topology stay UNKNOWN
        # UNKNOWN + has optics = stays UNKNOWN (flag for manual review)

    # Collect stats before stripping
    canonical_counts = result["STATUS_CANONICAL"].value_counts()
    rows_stripped = int(canonical_counts.get(SECTION_HEADER, 0))
    rows_blank = int(canonical_counts.get(BLANK, 0))

    # Collect unknown statuses for logging
    unknown_mask = result["STATUS_CANONICAL"] == UNKNOWN
    unknown_statuses = []
    if unknown_mask.any():
        unknown_vals = result.loc[unknown_mask, status_col].value_counts()
        unknown_statuses = [(val, int(cnt)) for val, cnt in unknown_vals.items()]
        for val, cnt in unknown_statuses:
            log.warning("UNKNOWN status value: %r (%d rows) — add to STATUS_MAP", val, cnt)

    # Collect section names for topology derivation
    section_mask = result["STATUS_CANONICAL"] == SECTION_HEADER
    section_names = sorted(result.loc[section_mask, status_col].unique().tolist())

    # Strip section header rows
    clean = result[result["STATUS_CANONICAL"] != SECTION_HEADER].copy()
    rows_clean = len(clean)

    log.info(
        "Preprocessor: %d original → %d clean (%d section headers stripped, %d blank, %d unknown)",
        rows_original, rows_clean, rows_stripped, rows_blank, len(unknown_statuses),
    )

    stats = {
        "rows_original": rows_original,
        "rows_stripped": rows_stripped,
        "rows_blank": rows_blank,
        "rows_clean": rows_clean,
        "unknown_statuses": unknown_statuses,
        "section_names": section_names,
    }

    return clean, stats


def count_optics_independently(df: pd.DataFrame) -> Dict[str, Dict[str, int]]:
    """Count A-OPTIC and Z-OPTIC as separate physical optics.

    Each non-empty cell in A-OPTIC is 1 optic.  Each non-empty cell in
    Z-OPTIC is 1 optic.  No deduplication, no COALESCE.

    Returns:
        {
            "by_type": {
                "OSFP-800G-2DR4": {"a_side": 19748, "z_side": 8656, "total": 28404},
                ...
            },
            "totals": {"a_side": 24451, "z_side": 24416, "grand_total": 48867}
        }
    """
    a_optic_col = _find_col(df, _A_OPTIC_CANDIDATES)
    z_optic_col = _find_col(df, _Z_OPTIC_CANDIDATES)

    by_type: Dict[str, Dict[str, int]] = defaultdict(lambda: {"a_side": 0, "z_side": 0, "total": 0})
    total_a = 0
    total_z = 0

    if a_optic_col:
        a_vals = df[a_optic_col].fillna("").astype(str).str.strip()
        a_vals = a_vals.where(a_vals.str.lower() != "nan", "")
        a_counts = a_vals[a_vals != ""].value_counts()
        for optic, count in a_counts.items():
            by_type[optic]["a_side"] += int(count)
            by_type[optic]["total"] += int(count)
            total_a += int(count)

    if z_optic_col:
        z_vals = df[z_optic_col].fillna("").astype(str).str.strip()
        z_vals = z_vals.where(z_vals.str.lower() != "nan", "")
        z_counts = z_vals[z_vals != ""].value_counts()
        for optic, count in z_counts.items():
            by_type[optic]["z_side"] += int(count)
            by_type[optic]["total"] += int(count)
            total_z += int(count)

    return {
        "by_type": dict(by_type),
        "totals": {
            "a_side": total_a,
            "z_side": total_z,
            "grand_total": total_a + total_z,
        },
    }


def preprocess_upload(filepath: str, sheet_name: Optional[str] = None) -> Dict[str, Any]:
    """Full preprocessing pipeline for an uploaded cutsheet.

    1. Reads the xlsx and finds the CUTSHEET tab
    2. Runs normalize_cutsheet_df (adds STATUS_CANONICAL, strips section headers)
    3. Runs count_optics_independently on the clean data
    4. Returns everything downstream code needs

    Returns:
        {
            "clean_df": pd.DataFrame,       # section headers removed
            "optic_counts": dict,            # from count_optics_independently
            "rows_stripped": int,
            "rows_clean": int,
            "unknown_statuses": list,
            "section_names": list,
            "sheet_name": str,               # which tab was used
        }
    """
    path = Path(filepath)
    if not path.exists():
        raise FileNotFoundError(f"Cutsheet not found: {filepath}")

    # Find the right sheet
    if sheet_name:
        tab = sheet_name
    else:
        tab = _find_cutsheet_tab(filepath)

    log.info("Preprocessing %s (tab: %s)", path.name, tab)

    df = pd.read_excel(filepath, sheet_name=tab, engine="openpyxl")

    # R37: Verify the tab has the columns we need before processing
    _verify_cutsheet_schema(df, tab)

    clean_df, stats = normalize_cutsheet_df(df)
    optic_counts = count_optics_independently(clean_df)

    log.info(
        "Optic counts: A=%d  Z=%d  Total=%d  Types=%d",
        optic_counts["totals"]["a_side"],
        optic_counts["totals"]["z_side"],
        optic_counts["totals"]["grand_total"],
        len(optic_counts["by_type"]),
    )

    return {
        "clean_df": clean_df,
        "optic_counts": optic_counts,
        "rows_stripped": stats["rows_stripped"],
        "rows_clean": stats["rows_clean"],
        "unknown_statuses": stats["unknown_statuses"],
        "section_names": stats["section_names"],
        "sheet_name": tab,
    }


def format_optic_count_text(optic_counts: Dict[str, Any]) -> str:
    """Format optic counts as human-readable text for the upload response.

    Matches the style of Define_Optic_Count.count_all_files_gui output
    so the frontend doesn't need changes.
    """
    lines = []
    by_type = optic_counts["by_type"]
    totals = optic_counts["totals"]

    # Sort by total count descending
    sorted_types = sorted(by_type.items(), key=lambda x: x[1]["total"], reverse=True)

    for optic, counts in sorted_types:
        lines.append(f"{optic}: {counts['total']}  (A: {counts['a_side']}, Z: {counts['z_side']})")

    lines.append("")
    lines.append(f"Total A-side optics: {totals['a_side']}")
    lines.append(f"Total Z-side optics: {totals['z_side']}")
    lines.append(f"Grand total optics:  {totals['grand_total']}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Tabs to skip — backup, legend, copy, and other non-data tabs
_SKIP_TAB_PATTERNS = (
    "legend", "backup", "copy of", "sheet", "overhead",
)


# Required column families for a valid cutsheet (R37)
_OPTIC_COLS = {"A-OPTIC", "A_OPTIC", "Z-OPTIC", "Z_OPTIC"}
_DEVICE_COLS = {
    "A-SIDE-DNS-NAME", "A-MODEL", "A-PORT",
    "Z-SIDE-DNS-NAME", "Z-MODEL", "Z-PORT",
    # Alternate naming
    "A SIDE DEVICE", "A MODEL", "A PORT",
}


def _verify_cutsheet_schema(df: pd.DataFrame, tab_name: str) -> None:
    """R37: Verify that the selected tab has optic AND device/port columns."""
    cols_upper = {c.upper().strip() for c in df.columns}
    has_optic = bool(cols_upper & {c.upper() for c in _OPTIC_COLS})
    has_device = bool(cols_upper & {c.upper() for c in _DEVICE_COLS})

    if not has_optic:
        raise ValueError(
            f"Tab '{tab_name}' has no optic columns (A-OPTIC / Z-OPTIC). "
            f"Columns found: {sorted(df.columns.tolist())[:10]}..."
        )
    if not has_device:
        raise ValueError(
            f"Tab '{tab_name}' has no device/port columns. "
            f"Columns found: {sorted(df.columns.tolist())[:10]}..."
        )


def _find_cutsheet_tab(filepath: str) -> str:
    """Find the best cutsheet tab in an xlsx file.

    Priority:
    1. CUTSHEET_CLEAN (preprocessed by Claude in Excel)
    2. CUTSHEET (standard name)
    3. First tab that isn't a skip-pattern match
    """
    xl = pd.ExcelFile(filepath, engine="openpyxl")
    names = xl.sheet_names
    xl.close()

    # Prefer pre-cleaned tab
    for name in names:
        if name.upper() == "CUTSHEET_CLEAN":
            return name

    # Standard cutsheet tab
    for name in names:
        if name.upper() == "CUTSHEET":
            return name

    # Fallback: first non-junk tab
    for name in names:
        lower = name.lower()
        if not any(pat in lower for pat in _SKIP_TAB_PATTERNS):
            return name

    # Last resort
    return names[0]
