"""
cutsheet_preprocessor.py — Automated cutsheet normalization at upload time.

Applies STATUS_MAP rules, strips section-header rows, counts A/Z optics
independently.  Source-agnostic: works on any DataFrame regardless of whether
it came from an xlsx upload or a Google Sheet fetch.

The canonical status mapping was generated by Claude in Excel from the
Ellendale MASTER-US-CENTRAL-08A cutsheet (2026-04-22).  New sites may
introduce unknown status values — those land as UNKNOWN and get logged so
the map can be expanded.
"""

from __future__ import annotations

import logging
import math
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Canonical status enum — the 8 possible values after normalization
# ---------------------------------------------------------------------------

COMPLETE = "COMPLETE"
NOT_TERMINATED = "NOT_TERMINATED"
NOT_RUN = "NOT_RUN"
# NOT_RUN_PRIORITY collapsed into NOT_RUN to match cutsheet_profiles.py
ADDITION = "ADDITION"
HUMAN_VERIFIED = "HUMAN_VERIFIED"
LLDP_PASSED = "LLDP_PASSED"
LLDP_FAILED = "LLDP_FAILED"
IN_PROGRESS = "IN_PROGRESS"
PENDING = "PENDING"
BLANK = "BLANK"
SECTION_HEADER = "SECTION_HEADER"
UNKNOWN = "UNKNOWN"

# ---------------------------------------------------------------------------
# STATUS_MAP — built from Claude in Excel output (171 rows, 2026-04-22)
#
# Keys are EXACT original status strings (case-sensitive match first,
# case-insensitive fallback).  Values are one of the canonical enums above.
# ---------------------------------------------------------------------------

STATUS_MAP: Dict[str, str] = {
    # ── Real cable statuses ──────────────────────────────────────────────
    "Cable Is Ran: Complete": COMPLETE,
    "Human Verified": HUMAN_VERIFIED,
    "Cable Is Ran: Not Terminated": NOT_TERMINATED,
    "Cable Not Run": NOT_RUN,
    "Cable Not Run: Priority": NOT_RUN,
    "Addition": ADDITION,
    # ── Canonical values (self-mapping for pre-cleaned sheets) ─────────
    "COMPLETE": COMPLETE,
    "NOT_TERMINATED": NOT_TERMINATED,
    "NOT_RUN": NOT_RUN,
    "NOT_RUN_PRIORITY": NOT_RUN,  # pre-cleaned sheets may have this value
    "ADDITION": ADDITION,
    "HUMAN_VERIFIED": HUMAN_VERIFIED,
    "LLDP_PASSED": LLDP_PASSED,
    "LLDP_FAILED": LLDP_FAILED,
    "IN_PROGRESS": IN_PROGRESS,
    "PENDING": PENDING,
    "BLANK": BLANK,
    # ── Fuzzy variants (lowercase keys for case-insensitive fallback) ────
    "cable is ran: complete": COMPLETE,
    "cable is ran complete": COMPLETE,
    "cable is ran:complete": COMPLETE,
    "cable is ran - complete": COMPLETE,
    "cable ran complete": COMPLETE,
    "cable complete": COMPLETE,
    "complete": COMPLETE,
    "human verified": HUMAN_VERIFIED,
    "human: verified": HUMAN_VERIFIED,
    "manually verified": HUMAN_VERIFIED,
    "cable is ran: not terminated": NOT_TERMINATED,
    "cable is ran not terminated": NOT_TERMINATED,
    "cable is ran:not terminated": NOT_TERMINATED,
    "cable is ran - not terminated": NOT_TERMINATED,
    "not terminated": NOT_TERMINATED,
    "cable not run": NOT_RUN,
    "cable not ran": NOT_RUN,
    "no cable": NOT_RUN,
    "cable not run: priority": NOT_RUN,
    "cable not run:priority": NOT_RUN,
    "cable not run - priority": NOT_RUN,
    "addition": ADDITION,
    "no label & not yet run": NOT_RUN,
    "no label and not yet run": NOT_RUN,
    # LLDP variants (from Quincy and other operational sites)
    # Kept as distinct canonical values so burndown/status queries can
    # distinguish LLDP-verified from cable-verified.
    "lldp: passed": LLDP_PASSED,
    "lldp:  passed": LLDP_PASSED,
    "lldp passed": LLDP_PASSED,
    "lldp:passed": LLDP_PASSED,
    "lldp - passed": LLDP_PASSED,
    "LLDP:  Passed": LLDP_PASSED,
    "LLDP Passed": LLDP_PASSED,
    "lldp: failed": LLDP_FAILED,
    "lldp:  failed": LLDP_FAILED,
    "lldp failed": LLDP_FAILED,
    "lldp:failed": LLDP_FAILED,
    "lldp - failed": LLDP_FAILED,
    "LLDP:  Failed": LLDP_FAILED,
    "LLDP Failed": LLDP_FAILED,
    # Misc statuses (from cutsheet_profiles.py)
    "in progress": IN_PROGRESS,
    "pending": PENDING,
}

# Build a lowercase lookup for case-insensitive fallback
_STATUS_MAP_LOWER: Dict[str, str] = {k.lower(): v for k, v in STATUS_MAP.items()}

# ---------------------------------------------------------------------------
# Site-specific section headers — keyed by site code (uppercase).
# These were previously embedded in STATUS_MAP but are Ellendale-specific.
# classify_status() checks this dict when STATUS_MAP returns UNKNOWN and a
# site_code is provided.  The _TOPOLOGY_PATTERN regex remains the universal
# fallback for sites without an explicit entry here.
# ---------------------------------------------------------------------------

SITE_SECTION_HEADERS: Dict[str, Dict[str, bool]] = {
    "ELD": {
        "BACKBONE BFR": True, "BACKBONE MGMT": True, "BACKBONE/OPTICAL MGMT": True,
        "CON-01 Grid A Pod 1": True, "CON-01 Grid A Pod 2": True,
        "CON-01 Grid A Pod 3": True, "CON-01 Grid A Pod 4": True,
        "CON-01 Grid A Rack 230": True,
        "CON-01 Grid A1 Rack 222": True, "CON-01 Grid A1 Rack 223": True,
        "CON-01 Grid A1 Rack 224": True, "CON-01 Grid A1 Rack 225": True,
        "CON-01 Grid A1 Rack 226": True, "CON-01 Grid A1 Rack 227": True,
        "CON-01 Grid A1 Rack 228": True, "CON-01 Grid A1 Rack 229": True,
        "CON-01 Grid A2 Rack 232": True, "CON-01 Grid A2 Rack 233": True,
        "CON-01 Grid A2 Rack 234": True, "CON-01 Grid A2 Rack 235": True,
        "CON-01 Grid A2 Rack 236": True, "CON-01 Grid A2 Rack 237": True,
        "CON-01 Grid A2 Rack 238": True, "CON-01 Grid A2 Rack 239": True,
        "CON-01 Grid A2 Rack 240": True,
        "CON-01 Grid B Pod 1": True, "CON-01 Grid B Rack 50": True,
        "CON-01 Grid B1 Rack 46": True,
        "CON-01 Grid C Rack 67": True, "CON-01 Grid C Rack 68": True,
        "CON-01 Grid C Rack 69": True, "CON-01 Grid C Rack 70": True,
        "CON-01 Grid C1": True, "CON-01 Grid C2": True, "CON-01 Grid C3": True,
        "CON-01 Grid D Rack 107": True, "CON-01 Grid D Rack 108": True,
        "CON-01 Grid D Rack 109": True, "CON-01 Grid D Rack 110": True,
        "CON-01 Grid D1": True, "CON-01 Grid D2": True, "CON-01 Grid D3": True,
        "CON-01 Grid E Pod 1": True, "CON-01 Grid E Rack 10": True,
        "CON-01 Grid E1 Rack 2": True, "CON-01 Grid E1 Rack 3": True,
        "CON-01 Grid E1 Rack 4": True, "CON-01 Grid E1 Rack 5": True,
        "Compute Mgmt In-Row Grid A1 Rack 222": True,
        "Compute Mgmt In-Row Grid A1 Rack 223": True,
        "Compute Mgmt In-Row Grid A1 Rack 224": True,
        "Compute Mgmt In-Row Grid A1 Rack 225": True,
        "Compute Mgmt In-Row Grid A1 Rack 226": True,
        "Compute Mgmt In-Row Grid A1 Rack 227": True,
        "Compute Mgmt In-Row Grid A1 Rack 228": True,
        "Compute Mgmt In-Row Grid A1 Rack 229": True,
        "Compute Mgmt In-Row Grid A2 Rack 232": True,
        "Compute Mgmt In-Row Grid A2 Rack 233": True,
        "Compute Mgmt In-Row Grid A2 Rack 234": True,
        "Compute Mgmt In-Row Grid A2 Rack 235": True,
        "Compute Mgmt In-Row Grid A2 Rack 236": True,
        "Compute Mgmt In-Row Grid A2 Rack 237": True,
        "Compute Mgmt In-Row Grid A2 Rack 238": True,
        "Compute Mgmt In-Row Grid A2 Rack 239": True,
        "Compute Mgmt In-Row Grid A2 Rack 240": True,
        "Compute Mgmt In-Row Grid B1 Rack 46": True,
        "Compute Mgmt In-Row Grid E1 Rack 2": True,
        "Compute Mgmt In-Row Grid E1 Rack 3": True,
        "Compute Mgmt In-Row Grid E1 Rack 4": True,
        "Compute Mgmt In-Row Grid E1 Rack 5": True,
        "DH202 :: <<<<< A1": True, "DH202 :: <<<<< A2": True,
        "DH202 :: <<<<< B1": True,
        "DH202 :: A3": True, "DH202 :: A4": True,
        "DH202 :: C1": True, "DH202 :: C2": True, "DH202 :: C3": True,
        "DH202 OVERFLOW T0 ROCE MGMT": True,
        "DH202 T1 ROCE MGMT": True, "DH202 T2 ROCE MGMT": True,
        "DH204 :: D1": True, "DH204 :: D2": True,
        "DH204 :: D3": True, "DH204 :: E1": True,
        "DH204 OVERFLOW T0 ROCE MGMT": True,
        "DH204 T1 ROCE MGMT": True, "DH204 T2 ROCE MGMT": True,
        "FBS": True,
        "GRID-AGG-A": True, "GRID-AGG-B": True, "GRID-AGG-C": True,
        "GRID-AGG-D": True, "GRID-AGG-E": True,
        "INFRA-DIST-A": True, "INFRA-DIST-B": True, "INFRA-DIST-C": True,
        "INFRA-DIST-D": True, "INFRA-DIST-E": True,
        "MGMT-CORE": True, "MGMT-DIST": True,
        "NET-01 Grid A Pod 1": True, "NET-01 Grid A Pod 2": True,
        "NET-01 Grid A Rack 230": True,
        "NET-01 Grid B Pod 1": True, "NET-01 Grid B Rack 50": True,
        "NET-01 Grid C Rack 67": True, "NET-01 Grid C Rack 68": True,
        "NET-01 Grid C Rack 69": True, "NET-01 Grid C Rack 70": True,
        "NET-01 Grid D Rack 107": True, "NET-01 Grid D Rack 108": True,
        "NET-01 Grid D Rack 109": True, "NET-01 Grid D Rack 110": True,
        "NET-01 Grid E Pod 1": True, "NET-01 Grid E Rack 10": True,
        "OOB-FW": True,
        "POD-DIST-C 1": True, "POD-DIST-C 2": True, "POD-DIST-C 3": True,
        "POD-DIST-D 1": True, "POD-DIST-D 2": True, "POD-DIST-D 3": True,
        "RACK 43 NET + CON": True, "RACK 44 NET + CON": True,
        "RACK 51 NET + CON": True, "RACK 52 NET + CON": True,
        "RACK 53 NET + CON": True, "RACK 54 NET + CON": True,
        "RACK 55 NET + CON": True, "RACK 56 NET + CON": True,
        "RACK 57 NET + CON": True, "RACK 58 NET + CON": True,
        "RACK 59 NET + CON": True,
        "ROCE INFRA AGGS DH202": True, "ROCE INFRA AGGS DH204": True,
        "STOR INFRA-DIST A3": True,
        "STOR NET-01 Grid A Pod 3": True, "STOR NET-01 Grid A Pod 4": True,
        "TIER-1 TO TIER-0 A1": True, "TIER-1 TO TIER-0 A2": True,
        "TIER-1 TO TIER-0 A3 (T0 MULTIPLIER X3)": True,
        "TIER-1 TO TIER-0 A4 (T0 MULTIPLIER X3)": True,
        "TIER-1 TO TIER-0 B1": True,
        "TIER-1 TO TIER-0 C1": True, "TIER-1 TO TIER-0 C2": True,
        "TIER-1 TO TIER-0 C3": True,
        "TIER-1 TO TIER-0 D1": True, "TIER-1 TO TIER-0 D2": True,
        "TIER-1 TO TIER-0 D3": True,
        "TIER-1 TO TIER-0 E1 (T0 MULTIPLIER X1)": True,
        "TIER-2 TO TIER-1 A": True, "TIER-2 TO TIER-1 B": True,
        "TIER-2 TO TIER-1 C": True, "TIER-2 TO TIER-1 D": True,
        "TIER-2 TO TIER-1 GRID:E (T1 MULTIPLIER X2)": True,
        "TIER-3 TO TIER-2 1 A": True, "TIER-3 TO TIER-2 1 B": True,
        "TIER-3 TO TIER-2 1 C": True, "TIER-3 TO TIER-2 1 D": True,
        "TIER-3 TO TIER-2 1 E": True,
    },
    # Orangeburg US-EAST-01A (DH1/DH2/DH3/DH4) — added 2026-04-28 from
    # MASTER-US-EAST-01A-US-OBG01-ORANGEBURG.xlsx upload.  Most of these
    # are also caught by _TOPOLOGY_PATTERN, but listed explicitly so the
    # data is self-documenting and so a future caller passing site_code
    # gets exact matching rather than relying on the regex.
    "OBG": {
        "DATA HALL 1": True, "DATA HALL 2": True, "DATA HALL 3 & 4": True,
        "OOB-FIREWALL": True, "BACKBONE MGMT": True,
        "MGMT-CORE": True, "MGMT-DIST": True,
        "R163 Net + Con": True, "R164 Net + Con": True,
        "UFM Patch": True, "FBS": True,
        "RACK 155": True, "RACK 156": True, "RACK 157": True, "RACK 158": True,
        # GG1 grids: A, B, C, D, F, G — NET / COMP at AGG and DIST tiers
        "NET-AGG GG1-A": True, "NET-AGG GG1-B": True, "NET-AGG GG1-C": True,
        "NET-AGG GG1-D": True, "NET-AGG GG1-G": True,
        "COMP-AGG GG1-A": True, "COMP-AGG GG1-B": True, "COMP-AGG GG1-C": True,
        "COMP-AGG GG1-D": True, "COMP-AGG GG1-G": True,
        "NET-DIST GG1-A1": True, "NET-DIST GG1-A2": True,
        "NET-DIST GG1-A3": True, "NET-DIST GG1-A4": True,
        "NET-DIST GG1-B1": True,
        "NET-DIST GG1-C1": True, "NET-DIST GG1-C2": True, "NET-DIST GG1-C3": True,
        "NET-DIST GG1-D1": True, "NET-DIST GG1-D2": True,
        "NET-DIST GG1-D3": True, "NET-DIST GG1-D4": True,
        "NET-DIST GG1-G": True,
        "COMP-DIST GG1-A1": True, "COMP-DIST GG1-A2": True,
        "COMP-DIST GG1-A3": True, "COMP-DIST GG1-A4": True,
        "COMP-DIST GG1-B1": True,
        "COMP-DIST GG1-C1": True, "COMP-DIST GG1-C2": True, "COMP-DIST GG1-C3": True,
        "COMP-DIST GG1-D1": True, "COMP-DIST GG1-D2": True,
        "COMP-DIST GG1-D3": True, "COMP-DIST GG1-D4": True,
        "COMP-DIST GG1-G": True,
        # DH1 row markers (row N; row N MGMT + CON variant)
        **{f"DH1 Row {n}": True for n in range(1, 25)},
        **{f"DH1 Row {n} MGMT + CON": True for n in range(1, 25)},
        # DH2 row markers (DH2 ROW N MGMT + CON; DH2 :: ROW-N)
        **{f"DH2 ROW {n} MGMT + CON": True for n in range(1, 25)},
        **{f"DH2 :: ROW-{n}": True for n in range(1, 25)},
        # DH3 row 2/5/6 patterns
        "DH3 :: GRID-AGG :: POD-DIST": True, "DH3 :: POD-DIST :: INFRA-DIST": True,
        "DH3 ROW 2 :: NET-01 :: POD-DIST/T2": True,
        "DH3 ROW 2 :: INFRA-DIST :: INFRA/BMC": True,
        "DH3 ROW 5:: INFRA-DIST :: INFRA/BMC": True,
        "DH3 ROW 6:: INFRA-DIST :: INFRA/BMC": True,
        "DH3 ROW 2 :: NET-01/CON-01 :: EOR/INFRA/BMC": True,
        "DH3 ROW 5 :: NET-01/CON-01 :: EOR/INFRA/BMC": True,
        "DH3 ROW 6 :: NET-01/CON-01 :: EOR/INFRA/BMC": True,
        "DH3 ROW 2 :: BMC :: PS-LOU": True,
        "DH3 ROW 5 :: BMC :: PS-LOU": True,
        "DH3 ROW 6 :: BMC :: PS-LOU": True,
        "DH3 :: ROW 2 :: T0 > NODE": True,
        "DH3 :: ROW 5 :: T0 > NODE": True,
        "DH3 :: ROW 6 :: T0 > NODE": True,
        "DH3 :: ROW 2 :: INFRA/BMC": True,
        "DH3 :: ROW 5 :: INFRA/BMC": True,
        "DH3 :: ROW 6 :: INFRA/BMC": True,
        # DH4 row 1/2/5/6 patterns (lowercase 'dh4' variant)
        "dh4 :: GRID-AGG :: POD-DIST": True, "dh4 :: POD-DIST :: INFRA-DIST": True,
        "dh4 ROW 2 :: NET-01 :: POD-DIST/T2": True,
        "dh4 ROW 1 :: INFRA-DIST :: INFRA/BMC": True,
        "dh4 ROW 2 :: INFRA-DIST :: INFRA/BMC": True,
        "dh4 ROW 5:: INFRA-DIST :: INFRA/BMC": True,
        "dh4 ROW 6:: INFRA-DIST :: INFRA/BMC": True,
        "dh4 ROW 5 :: NET-01/CON-01 :: EOR/INFRA/BMC": True,
        "dh4 ROW 6 :: NET-01/CON-01 :: EOR/INFRA/BMC": True,
        "dh4 ROW 1 :: BMC :: PS-LOU": True,
        "dh4 ROW 2 :: BMC :: PS-LOU": True,
        "dh4 ROW 5 :: BMC :: PS-LOU": True,
        "dh4 ROW 6 :: BMC :: PS-LOU": True,
        "dh4 :: ROW 1 :: T0 > NODE": True,
        "dh4 :: ROW 2 :: T0 > NODE": True,
        "dh4 :: ROW 5 :: T0 > NODE": True,
        "dh4 :: ROW 6 :: T0 > NODE": True,
        "dh4 :: ROW 1 :: INFRA/BMC": True,
        "dh4 :: ROW 2 :: INFRA/BMC": True,
        "dh4 :: ROW 5 :: INFRA/BMC": True,
        "dh4 :: ROW 6 :: INFRA/BMC": True,
        # TIER patterns — Grid F and Grid G additions
        "TIER 4 to TIER 3 GG1": True,
        "TIER 3 to TIER 2 GG1-A": True, "TIER 3 to TIER 2 GG1-B": True,
        "TIER 3 to TIER 2 GG1-C": True, "TIER 3 to TIER 2 GG1-D": True,
        "TIER 2 to TIER 1 GG1-D1": True,
        "TIER 1 to TIER 0 GG1-D1": True, "TIER 1 to TIER 0 GG1-D2": True,
        "TIER 1 to TIER 0 GG1-D3": True, "TIER 1 to TIER 0 GG1-D4": True,
        "TIER-2 to TIER-1 GG1 A": True, "TIER-2 to TIER-1 GG1 B": True,
        "TIER-2 to TIER-1 GG1 C": True, "TIER-2 to TIER-1 GG1 G": True,
        "TIER-1 to TIER-0 GG1 a1": True, "TIER-1 to TIER-0 GG1 a2": True,
        "TIER-1 to TIER-0 GG1 A3": True, "TIER-1 to TIER-0 GG1 A4": True,
        "TIER-1 to TIER-0 GG1 B1": True,
        "TIER-1 to TIER-0 GG1 c1": True, "TIER-1 to TIER-0 GG1 c2": True,
        "TIER-1 to TIER-0 GG1 c3": True, "TIER-1 to TIER-0 GG1 G": True,
        "TIER-3 TO TIER-2 GG1 F": True, "TIER-3 TO TIER-2 GG1 G": True,
        "TIER-2 TO TIER-1 GG1 E": True, "TIER-2 TO TIER-1 GG1 F": True,
        "TIER-1 TO TIER-0 GG1 E1": True, "TIER-1 TO TIER-0 GG1 F1": True,
    },
}

# ---------------------------------------------------------------------------
# Optic column names — these are the raw column names we look for
# ---------------------------------------------------------------------------

_A_OPTIC_CANDIDATES = ("A-OPTIC", "A_OPTIC", "a-optic", "a_optic")
_Z_OPTIC_CANDIDATES = ("Z-OPTIC", "Z_OPTIC", "z-optic", "z_optic")
_STATUS_CANDIDATES = ("STATUS", "status", "Status")

# Breakout / loc / port column candidates — Excel headers use newline-wrapped
# text; normalised forms use a single space.  Both are listed so _find_col
# works regardless of whether the DataFrame came from a raw xlsx read (which
# preserves the literal \n) or from a pre-processed source that normalised
# the header text.
_A_BREAKOUT_LOC_CANDIDATES = (
    "A-BREAKOUT\nLOC:CAB:RU", "A-BREAKOUT LOC:CAB:RU",
    "A_BREAKOUT_LOC", "a-breakout\nloc:cab:ru", "a-breakout loc:cab:ru",
)
_Z_BREAKOUT_LOC_CANDIDATES = (
    "Z-BREAKOUT\nLOC:CAB:RU", "Z-BREAKOUT LOC:CAB:RU",
    "Z_BREAKOUT_LOC", "z-breakout\nloc:cab:ru", "z-breakout loc:cab:ru",
)
_A_LOC_CANDIDATES = ("A-LOC:CAB:RU", "A_LOC", "a-loc:cab:ru")
_A_PORT_CANDIDATES = ("A-PORT", "A_PORT", "a-port")
_Z_LOC_CANDIDATES = ("Z-LOC:CAB:RU", "Z_LOC", "z-loc:cab:ru")
_Z_PORT_CANDIDATES = ("Z-PORT", "Z_PORT", "z-port")


def _find_col(df: pd.DataFrame, candidates: tuple) -> Optional[str]:
    """Return the first column name from candidates that exists in df."""
    for c in candidates:
        if c in df.columns:
            return c
    return None


def _safe_str(val) -> str:
    """Convert a value to string, treating NaN/None as empty."""
    if val is None:
        return ""
    if isinstance(val, float) and math.isnan(val):
        return ""
    return str(val).strip()


# ---------------------------------------------------------------------------
# R36: Topology name patterns for section header promotion
# Only UNKNOWN+empty-optic rows matching these patterns get promoted to
# SECTION_HEADER.  Everything else stays UNKNOWN.
# ---------------------------------------------------------------------------

import re as _re

_TOPOLOGY_PATTERN = _re.compile(
    r"(?i)"
    r"(?:"
    r"TIER|GRID|CON-\d|NET-\d|RACK\s*\d|DH\d|SPINE|LEAF|FDP|CDU|PDU|TOR|"
    r"FBS|MGMT|DIST|AGG|ROCE|INFRA|BACKBONE|STOR|POD-DIST|OOB|NVLINK|GPU|"
    r"OVERFLOW|LOCODE|"
    # Orangeburg additions (2026-04-28): "DATA HALL N" headers, racks
    # numbered as R163/R164 (rather than RACK 163), and UFM Patch panel.
    r"DATA\s*HALL|R\d{2,4}\s+(?:Net|MGMT|CON)|UFM"
    r")",
)

# ---------------------------------------------------------------------------
# Core functions
# ---------------------------------------------------------------------------

def classify_status(raw_status: str, site_code: Optional[str] = None) -> str:
    """Map a raw STATUS string to a canonical value.

    Resolution order:
    1. Exact match against STATUS_MAP
    2. Case-insensitive match against _STATUS_MAP_LOWER
    3. Site-specific section header lookup via SITE_SECTION_HEADERS (if site_code given)
    4. Return UNKNOWN (caller decides what to do)
    """
    if not raw_status:
        return BLANK
    if raw_status in STATUS_MAP:
        return STATUS_MAP[raw_status]
    lower = raw_status.lower().strip()
    if not lower:
        return BLANK
    result = _STATUS_MAP_LOWER.get(lower, UNKNOWN)
    if result == UNKNOWN and site_code:
        site_headers = SITE_SECTION_HEADERS.get(site_code.upper(), {})
        if raw_status in site_headers:
            return SECTION_HEADER
    return result


def normalize_cutsheet_df(df: pd.DataFrame, site_code: Optional[str] = None) -> Tuple[pd.DataFrame, Dict[str, Any]]:
    """Normalize a raw cutsheet DataFrame.

    Adds STATUS_CANONICAL column, identifies section headers vs real data,
    and strips section-header rows.

    Returns:
        (clean_df, stats) where stats has keys:
        - rows_original: total rows in input
        - rows_stripped: section header rows removed
        - rows_blank: rows with BLANK status
        - rows_clean: rows in output
        - unknown_statuses: list of (value, count) for any UNKNOWN mappings
        - section_names: list of section header values found (for topology)
    """
    status_col = _find_col(df, _STATUS_CANDIDATES)
    if status_col is None:
        log.warning("No STATUS column found in DataFrame — skipping normalization")
        return df.copy(), {
            "rows_original": len(df),
            "rows_stripped": 0,
            "rows_blank": 0,
            "rows_clean": len(df),
            "unknown_statuses": [],
            "section_names": [],
        }

    result = df.copy()
    rows_original = len(result)

    # Vectorized: clean the status column
    raw_status = result[status_col].fillna("").astype(str).str.strip()
    # Replace "nan" strings from pandas NaN conversion
    raw_status = raw_status.where(raw_status.str.lower() != "nan", "")

    # Classify each status value — vectorized via .map() with fallback
    # Build a unique-value mapping to avoid per-row function calls
    unique_vals = raw_status.unique()
    val_to_canonical = {}
    for v in unique_vals:
        val_to_canonical[v] = classify_status(v, site_code=site_code)

    result["STATUS_CANONICAL"] = raw_status.map(val_to_canonical)

    # Heuristic fallback for UNKNOWN: if optic columns are both empty,
    # it's almost certainly a section header
    a_optic_col = _find_col(result, _A_OPTIC_CANDIDATES)
    z_optic_col = _find_col(result, _Z_OPTIC_CANDIDATES)

    if a_optic_col and z_optic_col:
        unknown_mask = result["STATUS_CANONICAL"] == UNKNOWN
        a_empty = result[a_optic_col].fillna("").astype(str).str.strip().eq("")
        z_empty = result[z_optic_col].fillna("").astype(str).str.strip().eq("")
        both_empty = a_empty & z_empty

        # R36: UNKNOWN + no optics + matches topology pattern = section header.
        # Without the topology check, notes rows and partial data rows get
        # wrongly promoted to section headers and stripped.
        candidates = unknown_mask & both_empty
        if candidates.any():
            topo_match = raw_status.str.contains(
                _TOPOLOGY_PATTERN, na=False
            )
            result.loc[candidates & topo_match, "STATUS_CANONICAL"] = SECTION_HEADER
            # Candidates that don't match topology stay UNKNOWN
        # UNKNOWN + has optics = stays UNKNOWN (flag for manual review)

    # Collect stats before stripping
    canonical_counts = result["STATUS_CANONICAL"].value_counts()
    rows_stripped = int(canonical_counts.get(SECTION_HEADER, 0))
    rows_blank = int(canonical_counts.get(BLANK, 0))

    # Collect unknown statuses for logging
    unknown_mask = result["STATUS_CANONICAL"] == UNKNOWN
    unknown_statuses = []
    if unknown_mask.any():
        unknown_vals = result.loc[unknown_mask, status_col].value_counts()
        unknown_statuses = [(val, int(cnt)) for val, cnt in unknown_vals.items()]
        for val, cnt in unknown_statuses:
            log.warning("UNKNOWN status value: %r (%d rows) — add to STATUS_MAP", val, cnt)

    # Collect section names for topology derivation
    section_mask = result["STATUS_CANONICAL"] == SECTION_HEADER
    section_names = sorted(result.loc[section_mask, status_col].unique().tolist())

    # Strip section header rows
    clean = result[result["STATUS_CANONICAL"] != SECTION_HEADER].copy()
    rows_clean = len(clean)

    log.info(
        "Preprocessor: %d original → %d clean (%d section headers stripped, %d blank, %d unknown)",
        rows_original, rows_clean, rows_stripped, rows_blank, len(unknown_statuses),
    )

    stats = {
        "rows_original": rows_original,
        "rows_stripped": rows_stripped,
        "rows_blank": rows_blank,
        "rows_clean": rows_clean,
        "unknown_statuses": unknown_statuses,
        "section_names": section_names,
    }

    return clean, stats


def count_optics_independently(df: pd.DataFrame) -> Dict[str, Dict[str, int]]:
    """Count A-OPTIC and Z-OPTIC as separate physical optics, with breakout deduplication.

    When a cable has a breakout panel (A-BREAKOUT LOC:CAB:RU is non-empty), the same
    A-side port fans out across multiple spreadsheet rows.  The A-optic is counted only
    once per unique A-LOC:CAB:RU + A-PORT combination.  The same deduplication applies
    to the Z-side when Z-BREAKOUT LOC:CAB:RU is non-empty.

    Returns:
        {
            "by_type": {
                "OSFP-800G-2DR4": {"a_side": 19748, "z_side": 8656, "total": 28404},
                ...
            },
            "totals": {"a_side": 24451, "z_side": 24416, "grand_total": 48867}
        }
    """
    a_optic_col    = _find_col(df, _A_OPTIC_CANDIDATES)
    z_optic_col    = _find_col(df, _Z_OPTIC_CANDIDATES)
    a_breakout_col = _find_col(df, _A_BREAKOUT_LOC_CANDIDATES)
    z_breakout_col = _find_col(df, _Z_BREAKOUT_LOC_CANDIDATES)
    a_loc_col      = _find_col(df, _A_LOC_CANDIDATES)
    a_port_col     = _find_col(df, _A_PORT_CANDIDATES)
    z_loc_col      = _find_col(df, _Z_LOC_CANDIDATES)
    z_port_col     = _find_col(df, _Z_PORT_CANDIDATES)

    by_type: Dict[str, Dict[str, int]] = defaultdict(lambda: {"a_side": 0, "z_side": 0, "total": 0})
    total_a = 0
    total_z = 0

    def _clean(col: str):
        vals = df[col].fillna("").astype(str).str.strip()
        return vals.where(vals.str.lower() != "nan", "")

    if a_optic_col:
        a_optic_vals = _clean(a_optic_col)
        if a_breakout_col and a_loc_col and a_port_col:
            a_breakout_vals = _clean(a_breakout_col)
            a_loc_vals      = _clean(a_loc_col)
            a_port_vals     = _clean(a_port_col)
            seen_a: set = set()
            for optic, breakout, loc, port in zip(
                a_optic_vals, a_breakout_vals, a_loc_vals, a_port_vals
            ):
                if not optic:
                    continue
                if breakout:
                    key = loc + "\x00" + port
                    if key in seen_a:
                        continue
                    seen_a.add(key)
                by_type[optic]["a_side"] += 1
                by_type[optic]["total"]  += 1
                total_a += 1
        else:
            # Breakout columns not found — fall back to counting every non-empty cell
            a_counts = a_optic_vals[a_optic_vals != ""].value_counts()
            for optic, count in a_counts.items():
                by_type[optic]["a_side"] += int(count)
                by_type[optic]["total"]  += int(count)
                total_a += int(count)

    if z_optic_col:
        z_optic_vals = _clean(z_optic_col)
        if z_breakout_col and z_loc_col and z_port_col:
            z_breakout_vals = _clean(z_breakout_col)
            z_loc_vals      = _clean(z_loc_col)
            z_port_vals     = _clean(z_port_col)
            seen_z: set = set()
            for optic, breakout, loc, port in zip(
                z_optic_vals, z_breakout_vals, z_loc_vals, z_port_vals
            ):
                if not optic:
                    continue
                if breakout:
                    key = loc + "\x00" + port
                    if key in seen_z:
                        continue
                    seen_z.add(key)
                by_type[optic]["z_side"] += 1
                by_type[optic]["total"]  += 1
                total_z += 1
        else:
            z_counts = z_optic_vals[z_optic_vals != ""].value_counts()
            for optic, count in z_counts.items():
                by_type[optic]["z_side"] += int(count)
                by_type[optic]["total"]  += int(count)
                total_z += int(count)

    return {
        "by_type": dict(by_type),
        "totals": {
            "a_side": total_a,
            "z_side": total_z,
            "grand_total": total_a + total_z,
        },
    }


def preprocess_upload(filepath: str, sheet_name: Optional[str] = None) -> Dict[str, Any]:
    """Full preprocessing pipeline for an uploaded cutsheet.

    1. Reads the xlsx and finds the CUTSHEET tab
    2. Runs normalize_cutsheet_df (adds STATUS_CANONICAL, strips section headers)
    3. Runs count_optics_independently on the clean data
    4. Returns everything downstream code needs

    Returns:
        {
            "clean_df": pd.DataFrame,       # section headers removed
            "optic_counts": dict,            # from count_optics_independently
            "rows_stripped": int,
            "rows_clean": int,
            "unknown_statuses": list,
            "section_names": list,
            "sheet_name": str,               # which tab was used
        }
    """
    path = Path(filepath)
    if not path.exists():
        raise FileNotFoundError(f"Cutsheet not found: {filepath}")

    # Find the right sheet
    if sheet_name:
        tab = sheet_name
    else:
        tab = _find_cutsheet_tab(filepath)

    log.info("Preprocessing %s (tab: %s)", path.name, tab)

    df = pd.read_excel(filepath, sheet_name=tab, engine="calamine")

    # R37: Verify the tab has the columns we need before processing
    _verify_cutsheet_schema(df, tab)

    clean_df, stats = normalize_cutsheet_df(df)
    optic_counts = count_optics_independently(clean_df)

    log.info(
        "Optic counts: A=%d  Z=%d  Total=%d  Types=%d",
        optic_counts["totals"]["a_side"],
        optic_counts["totals"]["z_side"],
        optic_counts["totals"]["grand_total"],
        len(optic_counts["by_type"]),
    )

    return {
        "clean_df": clean_df,
        "optic_counts": optic_counts,
        "rows_stripped": stats["rows_stripped"],
        "rows_clean": stats["rows_clean"],
        "unknown_statuses": stats["unknown_statuses"],
        "section_names": stats["section_names"],
        "sheet_name": tab,
    }


def format_optic_count_text(optic_counts: Dict[str, Any]) -> str:
    """Format optic counts as human-readable text for the upload response.

    Matches the style of Define_Optic_Count.count_all_files_gui output
    so the frontend doesn't need changes.
    """
    lines = []
    by_type = optic_counts["by_type"]
    totals = optic_counts["totals"]

    # Sort by total count descending
    sorted_types = sorted(by_type.items(), key=lambda x: x[1]["total"], reverse=True)

    for optic, counts in sorted_types:
        lines.append(f"{optic}: {counts['total']}  (A: {counts['a_side']}, Z: {counts['z_side']})")

    lines.append("")
    lines.append(f"Total A-side optics: {totals['a_side']}")
    lines.append(f"Total Z-side optics: {totals['z_side']}")
    lines.append(f"Grand total optics:  {totals['grand_total']}")
    lines.append("")
    lines.append(
        "Note: A-side optics on breakout fan-out rows are deduplicated by port key "
        "(one physical optic per A-LOC:CAB:RU + A-PORT). Z-side breakouts are "
        "deduplicated similarly."
    )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Tabs to skip — backup, legend, copy, and other non-data tabs
_SKIP_TAB_PATTERNS = (
    "legend", "backup", "copy of", "sheet", "overhead",
    "summary", "status_map", "host_inventory", "burndown",
    "site-hosts", "device_inventory", "connections", "site hosts", "hosts",
)


# Required column families for a valid cutsheet (R37)
_OPTIC_COLS = {"A-OPTIC", "A_OPTIC", "Z-OPTIC", "Z_OPTIC"}
_DEVICE_COLS = {
    "A-SIDE-DNS-NAME", "A-MODEL", "A-PORT",
    "Z-SIDE-DNS-NAME", "Z-MODEL", "Z-PORT",
    # Alternate naming
    "A SIDE DEVICE", "A MODEL", "A PORT",
}


def _verify_cutsheet_schema(df: pd.DataFrame, tab_name: str) -> None:
    """R37: Verify that the selected tab has optic AND device/port columns."""
    cols_upper = {c.upper().strip() for c in df.columns}
    has_optic = bool(cols_upper & {c.upper() for c in _OPTIC_COLS})
    has_device = bool(cols_upper & {c.upper() for c in _DEVICE_COLS})

    if not has_optic:
        raise ValueError(
            f"Tab '{tab_name}' has no optic columns (A-OPTIC / Z-OPTIC). "
            f"Columns found: {sorted(df.columns.tolist())[:10]}..."
        )
    if not has_device:
        raise ValueError(
            f"Tab '{tab_name}' has no device/port columns. "
            f"Columns found: {sorted(df.columns.tolist())[:10]}..."
        )


def _find_cutsheet_tab(filepath: str) -> str:
    """Find the best cutsheet tab in an xlsx file.

    Priority:
    1. CUTSHEET_CLEAN (preprocessed by Claude in Excel)
    2. CUTSHEET (standard name)
    3. First tab that isn't a skip-pattern match
    """
    xl = pd.ExcelFile(filepath, engine="calamine")
    names = xl.sheet_names
    xl.close()

    selected = None
    for name in names:
        if name.upper() == "CUTSHEET_CLEAN":
            selected = name
            break
    if selected is None:
        for name in names:
            if name.upper() == "CUTSHEET":
                selected = name
                break
    if selected is None:
        for name in names:
            if not any(pat in name.lower() for pat in _SKIP_TAB_PATTERNS):
                selected = name
                break
    if selected is None:
        selected = names[0]

    log.info("Selected tab: %r from %d available tabs", selected, len(names))
    return selected
