apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "atlas.fullname" . }}-uploads
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.uploads.storageClass }}
  storageClassName: {{ .Values.uploads.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.uploads.size }}
